sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g snyk
before_script:
  - npm prune
  - snyk auth ${SNYK_API_KEY} -q
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
